apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-service-prod
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: bot-service-prod
  template:
    metadata:
      labels:
        app: bot-service-prod
    spec:
      serviceAccountName: sendme
      containers:
        - name: bot-service-prod
          image: 796834059009.dkr.ecr.eu-west-1.amazonaws.com/bot-service:$BUILD_NUMBER
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: credentials  

